# syntax=docker/dockerfile:1

# to add config, use docker env flag when running container: --env-file env_dev.txt

FROM python:3.8-slim-buster

WORKDIR /docker-flask

COPY requirements.txt requirements.txt

COPY llama3-8b-awq/ llama3-8b-awq

COPY prompts.json prompts.json


RUN pip3 install -r requirements.txt
COPY . .

#ENTRYPOINT ["python3"]
EXPOSE 80
CMD ["python3", "-u", "server.py"]