# Status codes and Code to Message map
CODE_SCRAPE_ALREADY_ATTEMPTED = -1
CODE_SUCCESS = 1
CODE_INVALID_FILE_ENDING_FOR_URL = 2
CODE_TIMEOUT = 3
CODE_INVALID_STATUS_CODE = 4
CODE_UNABLE_TO_PARSE = 5
CODE_URL_NAME_TOO_LONG = 6
CODE_URL_NOT_PUBLICILY_ACCESSIBLE = 7


# For visualization
RE_URL_DESC = "(\/submissions\/).{24}"

