FROM nginx:alpine
COPY nginx-prod.conf /etc/nginx/nginx.conf
COPY letsencrypt-domain.pem /etc/ssl/private/letsencrypt-domain.pem
COPY letsencrypt-domain.key /etc/ssl/private/letsencrypt-domain.key
RUN apk update && apk add bash
